### ISSUE TITLE
Fix some recurring errors in logs

### ISSUE THREAD

**Issue by sylvain-morin** [inaturalist/iNaturalistAPI#381]
Some errors are recurring in pm2 logs:

- [ ] express deprecated req.host: Use req.hostname instead at node_modules/lodash/lodash.js:4837:28

- [ ] Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.

- [ ] [0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: 2015-2-1, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (/home/inaturalist/deployment/api/releases/20230511181643/node_modules/moment/moment.js:324:25)
    at configFromString (/home/inaturalist/deployment/api/releases/20230511181643/node_modules/moment/moment.js:2550:19)
    at configFromInput (/home/inaturalist/deployment/api/releases/20230511181643/node_modules/moment/moment.js:2993:13)
    at prepareConfig (/home/inaturalist/deployment/api/releases/20230511181643/node_modules/moment/moment.js:2976:13)
    at createFromConfig (/home/inaturalist/deployment/api/releases/20230511181643/node_modules/moment/moment.js:2943:44)
    at createLocalOrUTC (/home/inaturalist/deployment/api/releases/20230511181643/node_modules/moment/moment.js:3037:16)
    at createLocal (/home/inaturalist/deployment/api/releases/20230511181643/node_modules/moment/moment.js:3041:16)
    at hooks (/home/inaturalist/deployment/api/releases/20230511181643/node_modules/moment/moment.js:16:29)
    at Object.ObservationQueryBuilder.reqToElasticQueryComponents (/home/inaturalist/deployment/api/releases/20230511181643/lib/models/observation_query_builder.js:278:40)
    at runMicrotasks (<anonymous>)

- [ ] (node:1230219) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time

**Comment by sylvain-morin** [comment]
Replaced by other ticket in chef-repo
